### ISSUE TITLE
Not working.......

### ISSUE THREAD

**Issue by Cabinfourus** [polihedron/DIY-Reflow-Oven#10]
I have built this thing and followed the guide with my build. I used the instructibles guide as the tutorial. 
I never could get mine to work. The Nextion display has the correct screens but the STM32 code never worked at all. I loaded the .bin file correctly (i think). I am not sure how to go in and rework the source code and program the STM32. Is there a guide to this?

**Comment by polihedron** [comment]
Hi there @Cabinfourus,
you're wasting your time (and mine also) with that kind of feedback: "not working...." or "never worked at all"
I can recommend you something like:
- check wiring again,
- have you tried turning off and on again?  
- that's odd mine is working..... 

Please put some efford to figure out yours build issue, I don't have crystal ball.
No time bandwidth here and motivation to help you when you are so lazy to find and read how to debug or how to flash stm32.

Kind Regards
