### ISSUE TITLE
How to add Time Line my oven slow up temp

### ISSUE THREAD

**Issue by Witawat** [polihedron/DIY-Reflow-Oven#12]
How to add Time Line my oven slow up temp use 1200w, but slow up hot temp
need time line over 800 S

i see code in here not sure for edit add
![image](https://github.com/polihedron/DIY-Reflow-Oven/assets/4926369/c27d1d2e-d099-48b5-a16b-889dbd6e3859)
![IMG_20231214_145443](https://github.com/polihedron/DIY-Reflow-Oven/assets/4926369/06b2b8f3-ea7a-46ef-80ea-647e6185d10d)

i use temp 0.3C /s 
and how to config P I D value

bug how to fix ?

![image](https://github.com/polihedron/DIY-Reflow-Oven/assets/4926369/aef9c1bf-ca90-4735-ab1b-baa1b7ae4075)

**Comment by polihedron** [comment]
I'm not sure, what you need.. 
another Time Line for 800s max?
To edit timeline you will need to replace 660s to 800s in the dx equation: dx = 275 / 800 / 2 = 0,171875
and also edit the nextion hmi file by replacing the background 0.png to new one with 800s time line values.

regarding to config pid values, it's not easy, depends from few things, 
start from P value 50 or simply go to wiki page 
https://en.wikipedia.org/wiki/Proportional–integral–derivative_controller
check manual tuning
