### ISSUE TITLE
How did you tune this oven?

### ISSUE THREAD

**Issue by mueti** [polihedron/DIY-Reflow-Oven#13]
Hi 
I have built this oven and it works so far.
But I am unable to tune the PID Controller so i does not overheat and is able to follow the curve.
I tried the CHR method but the results i got do not match the settings on the oven.
What was your method?

**Comment by polihedron** [comment]
Hi there, 
my method was quite easy, I used PID values from other users who build this oven in comments section Vulcans instructable. I just put them and it was working out of the box.:)
TBH I did cosmetics changes using manual PID tuning, like described on wiki:

![PID_Compensation_Animated](https://github.com/polihedron/DIY-Reflow-Oven/assets/46649005/9aba0b9f-b103-401d-abc4-42cf104fd60e)

in my opinion it's not easy to calibrate when you don't have build in fan, low power heaters  (below 1000W), non heat isolated chamber etc.

**Comment by mueti** [comment]
Hi thanks a lot
I will try that, in school we learnd theoretically how to use the CHR method but that did not work well.
