### ISSUE TITLE
Incorrect RX / TX in schematic

### ISSUE THREAD

**Issue by daestx** [polihedron/DIY-Reflow-Oven#14]
I guess the RX TX line needs to be switched in the schematic:

![image](https://github.com/user-attachments/assets/ecfef443-f52c-4b14-9782-30a0fe7c1d85)

RX needs to be connected with TX of the display and TX with RX.

**Comment by polihedron** [comment]
Hi there,
why RX / TX lines needs to be double crossed?
check RX and TX at display and level shifter:
level shifter TX_5V -> Nextion RX, level shifter RX_5V -> Nextion TX.

**Comment by daestx** [comment]
Oh yes, you're right, on your schematic, it is crossed at the display side.  Then I take it back and you may close this ticket. Sorry about it.
