### ISSUE TITLE
On which port is connected the Buzzer ?

### ISSUE THREAD

**Issue by joelv1964** [polihedron/DIY-Reflow-Oven#2]
Hi Polihedron, I have not yet started building my oven or its control electronics.  I really appreciate your idea of ​​adding a Buzzer, but can you tell which port of the STM32 it is connected to and if it is connected directly to it?  Thank you in advance for your answer.  Joel

**Comment by polihedron** [comment]
Hi there, soon I will update schematics to my mod. 
Buzzer is connected via one of the 4 channel level shifter module mosfets to PA15.
(Need to remove one of the resistors and cut the trace on the pcb.)
But I belive it's not necessary if buzzer when active consume less than 20mA, I just didn't want to leave any mosfet useless.:)
![IMG_20210704_104110_cr](https://user-images.githubusercontent.com/46649005/135428728-ae7609ba-1c1c-4b0c-9f16-5ce6d81db648.jpg)

**Comment by joelv1964** [comment]
Great !  thank you so much.  I hadn't thought of using the second part of the shield ...
Have a good day !

**Comment by daestx** [comment]
Maybe just an additional comment for the level shifter modification, when you would just like to use it as Mosfet to switch the Buzzer 5V. Here you can find a standard level shifter schematic:

![image](https://github.com/user-attachments/assets/7b5152d9-9b6d-4b5e-ad51-7c6af9b17394)

So, in principle you need just to cut the LV connector and remove R4. LV1 pin needs to be connected to GND

![image](https://github.com/user-attachments/assets/1425c829-175d-4b81-8943-08ff38697e25)

![image](https://github.com/user-attachments/assets/aede7661-a690-48ed-8816-1a9e875621e1)
