### ISSUE TITLE
No temperature number show up

### ISSUE THREAD

**Issue by botio** [polihedron/DIY-Reflow-Oven#3]
I wired everything and flash the firmware to the blue pill and the NEXTION display, but there is not temperature number just show up empty UI... and I have tried to find out for two days... even tried another blue pill... please help me!

**Comment by polihedron** [comment]
It's hard to guess, 
- make sure that connections are ok, 
- with USB to UART converter check that nextion can read and send data, 
- the same with bluepill, connect converter to bluepill and try to send commands via terminal.
- replace level shifter module
- switch rx with tx
- flash 1.1 version firmware (without modifications, maybe binary is the cause)
- compile source and flash bluepill using STM32CubeIDE
- check all connections again, and again.
It's quite simple mod, if you follow all steps from Vulcaman's instructables then it should be working.

**Comment by botio** [comment]
Thank you so much, I found the solution is to clean the flash first and reprogram it with v1.1 bin file. Everything works fine now. next step is adding fan ... or not.

**Comment by polihedron** [comment]
Adding fan can be tricky, because air temperature is quite high, easier and probably cheaper method is to look for convection oven, or find some replacement fan of the convection oven (they has metal sheet blades).
