### ISSUE TITLE
how to add "reflow profiles" into 1.1 firmware

### ISSUE THREAD

**Issue by botio** [polihedron/DIY-Reflow-Oven#4]
seems like only the original 1.1 firmware working for me to read the temp number, but I do really want to add the reflow profiles from "DIY-Reflow_Oven" like "lead 183" and other profiles. Could you let me know which file or which parts I should add to the 1.1 sources and build for adding this function? thank you so much.

**Comment by polihedron** [comment]
This repo contains my changes, if you look closer you will find commits and modifications in code of the initial version 1.1.
To make mod complete you will need to flash:
- bluepill using binary version 1.2, 
- nextion display with mod hmi file
Recent hmi and bin files are on releases page.
If you want to build and flash from sources then just download and open project in STM32CubeIDE. 
(That is needed if you want to set different default values of reflow parameters.)
Names of the folders are self-explanatory.

**Comment by botio** [comment]
Hi, after tried the release 1.2 which with the bin file or the one I build from sources code, it’s not working with the mod display. The tricky part is the mod display(1.2) is only working with the original 1.1 blue pill for me. I don’t understand why and how …  there is no error from build log… is it because I didn’t wire buzzer?

**Comment by polihedron** [comment]
I think you're doing something wrong. If you're using v1.2 hmi file with stm v1.1 binary, then you got chart temperature and time incorrect. Open project again in STM32CubeIDE, switch from release to debug and try to compile, then flash with full erase. It's crucial to use the same binary versions for nextion and bluepill.
Buzzer is just an output, no need to wire for the first run, especially when you're flashing blue pill stm32 with 1.1 version.
(v1.1 has no code for buzzer)

**Comment by botio** [comment]
this drives me crazy... I check all the wires again, and everything is exactly like the diagram u provide... but just can't get the stm v1.2 run with mod display.... and I did try the debug and release build like u said ... 

my processing order is built in CUBEIDE and get the bin file for st-link utility > full earse> programming. 

original 1.1 hmi and stm v1.1 working fine for me ... so maybe I should stick with it .... even tho I really want ur improvement.

**Comment by polihedron** [comment]
I have no idea why you have issues with project, already checked two stm32 bluepill boards, it's working like a charm.
Like I wrote this is quite simple mod, copy/paste code from main.c and main.h files to version 1.1, add output to PA15, or comment lines with buzzer, compile and flash, if no errors or warnings, you will get my mod version 1.2.

**Comment by botio** [comment]
The only thing I think may cause problem is my levelshifter 4ch, which may not like urs. Otherwise, there is no way display can't get number from bluebill. And thank you so much for your help.
