### ISSUE TITLE
Keypad is not reacted

### ISSUE THREAD

**Issue by VCO34** [polihedron/DIY-Reflow-Oven#6]
Hello, i was testing release version 1.3, but it dont has implemented support Keypad for update profile. Is it possible ? I visited to your code and e.g. command from keypad "p1b01" is not find.  Do you have going to plan implemented ?

**Comment by polihedron** [comment]
Hi there,
p1b01 is button on page 1 - keypad, for page1 is HandleKeyPad() function and that is the same as initial release. 
No need to code separately every keypad button. Just the special ones like enter, or clear. Rest of them - numbers are managed in loop, Handlekeypad() returns value from keypad, it's working in v1.3 just as in yt video.
To switch - update, or save reflow profile you will need p3b08 ... p3b11 buttons, saving is when you hold them for more than 3000ms, so nextion display sends commands: p3bs0 ... p2bs3.

Check touchpad on nextion display with nextion software in debug mode, or with usb to UART converter. I suspect issues with touch module, or frame for display is to close to touch screen.

**Comment by VCO34** [comment]
Hi, problem is in release file Reflow_Oven_STM32.v1.3.bin. If i upload  file with STM32CubeProgrammer, keypad is not function. If i compile source code and upload. Keypad is fuction correct. :) Otherwise thanks for your work

**Comment by polihedron** [comment]
That's odd, both binary files: debug and release are working on my stm32 dev board. 
At first run did you have blue line reflow profile, and temperature readings on the nextion display?
What stm32 dev board do you have? 
Did you full erase memory before flashing?

**Comment by VCO34** [comment]
Hi, first run was not problem. Temperature showed correct, by push START button started draw red line chart. I am using BluePill ARM STM32 STM32F103C8, maybe china clone. My setting CubeProbrammer - Skip flash erase before programming (OFF), Verify programming (ON), Run after programming (ON). For programing i used STlink V3 programmer.

**Comment by VCO34** [comment]
Very interesting problem. If I generate RS *.bin file with my STMCubeIDE. I upload file with CubeProgrammer. Keypad is not function. If I build and upload with STMCubeIDE, keypad is function. I am sending my RS file for test for you. 

https://uloz.to/tamhle/FdbzSdNu88f6/name/Nahrano-13-1-2022-v-10-29-47#!ZJWvAQR1AQt2BQNlA2IvAGpmZGV3AzL4BQSnDxI6A1RlBJMz

**Comment by polihedron** [comment]
I think I fixed this, quite interesting case, because of compilation optimalization level: Optimalize for size -Os, and any other than debug and none, UART_Recieved_Flag was lost somewhere,"volatile" at the variable fixed this.

**Comment by PricelessToolkit** [comment]
Thanks!!
